// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qdtxzdfkjstfxvjrzswf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFkdHh6ZGZranN0Znh2anJ6c3dmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMTQwMzIsImV4cCI6MjA2Mjc5MDAzMn0.YnRJt5JR3kGdp0mosT0DUVfJ1LmcCNTgyQIET9V356o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);